name: thrive_mobile_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.0
<<<<<<< HEAD
  go_router: ^3.1.0
=======
>>>>>>> d441c2ad7b8c50af11a5447ed65e77abb0927ca2
  flutter_riverpod: ^1.0.3
  upgrader: ^3.14.0
  shared_preferences: ^2.0.13
  firebase_core: ^1.12.0
<<<<<<< HEAD
  firebase_messaging: ^11.2.6
=======
  firebase_messaging: ^11.2.7
>>>>>>> d441c2ad7b8c50af11a5447ed65e77abb0927ca2
  easy_localization: ^3.0.0
  webview_flutter: ^3.0.2
  # lazy_load_scrollview: ^1.3.0
  # firebase_analytics: ^9.1.1
<<<<<<< HEAD
  fluttertoast: ^8.0.9
=======
>>>>>>> d441c2ad7b8c50af11a5447ed65e77abb0927ca2
  connectivity_plus: ^2.3.0
  google_fonts: 2.2.0
  cached_network_image: ^3.2.0
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  
  freezed: ^2.0.3
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6
  flutter_gen_runner:
<<<<<<< HEAD
  firebase_messaging_platform_interface: 3.1.6
=======
>>>>>>> d441c2ad7b8c50af11a5447ed65e77abb0927ca2

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logos/splash_screen_logo.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
    - assets/logos/

